all:
  children:
    bastion:
      hosts:
        bastion01:
          ansible_host: 10.220.100.10
          ansible_connection: local
    web:
      hosts:
        web01:
          ansible_host: 10.220.100.11
    was:
      hosts:
        was01:
          ansible_host: 10.220.100.21
        was02:
          ansible_host: 10.220.100.22
    db:
      hosts:
        db01:
          ansible_host: 10.220.100.31
          postgresql_role: primary
        db02:
          ansible_host: 10.220.100.32
          postgresql_role: standby
